apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: ccflock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: asingh1229/account-service:latest
          ports:
            - containerPort: 9000
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgres;Port=5432;Database=accountsdb;Username=shubh;Password=8342AdksnAKe"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: ccflock
spec:
  selector:
    app: account-service
  ports:
    - port: 9000
