apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  namespace: ccflock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          image: asingh1229/login-service:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: ccflock
spec:
  selector:
    app: login-service
  ports:
    - name: "http"
      port: 80
    - name: "https"
      port: 443
