apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: ccflock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "shubh"
            - name: POSTGRES_PASSWORD
              value: "8342AdksnAKe"
            - name: POSTGRES_DB
              value: "accountsdb"
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ccflock
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
