services:

    account-service:
        platform: linux/amd64
        build:
            context: ../AccountService
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        environment:
            - ConnectionStrings__DefaultConnection=Host=ccflock-db;Port=5432;Database=ccflockdb;Username=shubh;Password=8342AdksnAKe
            - Jwt__Key=7bATceklEQce5y28HMFU1YwYJcBna4Jz
        depends_on:
            - profile-service
        networks:
            - ccflocknet
    
    login-service:
        platform: linux/amd64
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - Jwt__Key=7bATceklEQce5y28HMFU1YwYJcBna4Jz
        build:
            context: ../
            dockerfile: LoginServices/Dockerfile
        ports:
            - "5001:80"
            - "5002:443"
        depends_on:
            - account-service
            - heartbeat-service
        networks:
            - ccflocknet
    
    heartbeat-service:
        platform: linux/amd64
        restart: unless-stopped
        environment:
            - Jwt__Key=7bATceklEQce5y28HMFU1YwYJcBna4Jz
        build:
            context: ../
            dockerfile: HeartBeatService/Dockerfile
        ports:
            - "9005:9005"
        depends_on:
            - redis
        networks:
            - ccflocknet
    
    hub-service:
        platform: linux/amd64
        build:
            context: ../
            dockerfile: HubService/Dockerfile
        environment:
            - Jwt__Key=7bATceklEQce5y28HMFU1YwYJcBna4Jz
        ports:
            - "5003:80"
            - "5004:443"
        depends_on:
            - login-service
            - heartbeat-service
        networks:
            - ccflocknet
    groupchat-service:
        platform: linux/amd64
        build:
            context: ../
            dockerfile: GroupchatService/Dockerfile
        environment:
            - Jwt__Key=7bATceklEQce5y28HMFU1YwYJcBna4Jz
        ports:
            - "5050:80"
            - "5051:443"
        depends_on:
            - heartbeat-service
            - redis
        networks:
            - ccflocknet
    privatechat-service:
        platform: linux/amd64
        build:
            context: ../
            dockerfile: PrivatechatService/Dockerfile
        environment:
            - Jwt__Key=7bATceklEQce5y28HMFU1YwYJcBna4Jz
            - HeartbeatService__Address=http://heartbeat-service:9005
        ports:
            - "5052:80"
            - "5053:443"
        depends_on:
            - heartbeat-service
            - redis
        networks:
            - ccflocknet

    redis:
        image: redis:7
        platform: linux/amd64
        container_name: online-users-redis-db
        
        ports:
            - "6379:6379"
        networks:
            - ccflocknet

    profile-service:
        platform: linux/amd64
        build:
            context: ../
            dockerfile: ProfileService/Dockerfile
        environment:
            - ConnectionStrings__DefaultConnection=Host=ccflock-db;Port=5432;Database=ccflockdb;Username=shubh;Password=8342AdksnAKe
            - Jwt__Key=7bATceklEQce5y28HMFU1YwYJcBna4Jz
        ports:
            - "5005:80"
            - "5006:443"
            - "9008:9008"
        volumes:
            - ../ProfileService/wwwroot/assets:/app/wwwroot/assets
        networks:
            - ccflocknet
    database-service:
        build:
            context: ../
            dockerfile: DatabaseService/Dockerfile
        ports:
            - "9011:9011"
        networks:
            - ccflocknet

    
    ccflock-db:
        image: postgres:15
        platform: linux/arm64
        restart: always
        environment:
            POSTGRES_USER: shubh
            POSTGRES_PASSWORD: 8342AdksnAKe
            POSTGRES_DB: ccflockdb
        ports:
            - "5439:5432"
        volumes:
            - ccflockpgdata:/var/lib/postgresql/data
        networks:
            - ccflocknet
        
    nginx:
        image: nginx:stable
        platform: linux/amd64
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../nginx/conf.d:/etc/nginx/conf.d:ro
            - ../Frontend:/usr/share/nginx/html:ro
            - ../nginx/certs:/etc/nginx/certs:ro
        depends_on:
            - login-service
            - heartbeat-service
            - account-service
        networks:
            - ccflocknet

volumes:
    pgdata:
    profilepgdata:
    ccflockpgdata:

networks:
    ccflocknet:
        external:
            true
